# Generated by Django 5.2.6 on 2025-09-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='wgs84_coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
