# Generated by Django 5.2.6 on 2025-10-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0002_alter_polygon_wgs84_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='wgs84_shp_dir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
