# Generated by Django 5.2.6 on 2025-09-23 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polygons', '0002_alter_polygon_wgs84_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDownloadTask',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='任务名称', max_length=200)),
                ('satellite', models.CharField(choices=[('sentinel-1', 'sentinel-1'), ('sentinel-2', 'sentinel-2'), ('smap', 'smap')], help_text='卫星类型', max_length=100)),
                ('start_time', models.DateTimeField(help_text='时间范围开始')),
                ('end_time', models.DateTimeField(help_text='时间范围结束')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('downloading', '下载中'), ('completed', '已完成'), ('partial_completed', '部分完成'), ('failed', '失败')], default='pending', help_text='任务状态', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='下载进度(百分比)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='完成时间', null=True)),
                ('error_message', models.TextField(blank=True, help_text='错误信息', null=True)),
                ('downloaded_images_count', models.IntegerField(default=0, help_text='下载的影像数量')),
                ('polygon', models.ForeignKey(help_text='目标多边形区域', on_delete=django.db.models.deletion.CASCADE, related_name='download_tasks', to='polygons.polygon')),
            ],
            options={
                'verbose_name': '影像下载任务',
                'verbose_name_plural': '影像下载任务',
                'db_table': 'image_download_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='影像名称', max_length=100)),
                ('shoot_time', models.DateTimeField(help_text='拍摄时间')),
                ('satellite', models.CharField(choices=[('sentinel-1', 'sentinel-1'), ('sentinel-2', 'sentinel-2'), ('smap', 'smap')], help_text='卫星类型', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='影像文件', null=True, upload_to='images/')),
                ('file_size', models.BigIntegerField(blank=True, help_text='文件大小(字节)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloud_coverage', models.FloatField(blank=True, help_text='云覆盖度(百分比)', null=True)),
                ('image_identifier', models.CharField(blank=True, help_text='卫星影像标识符', max_length=200, null=True)),
                ('download_url', models.URLField(blank=True, help_text='原始下载链接', null=True)),
                ('task', models.ForeignKey(help_text='来源下载任务', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.imagedownloadtask')),
            ],
            options={
                'verbose_name': '卫星影像',
                'verbose_name_plural': '卫星影像',
                'db_table': 'satellite_images',
                'ordering': ['-shoot_time'],
            },
        ),
    ]
