# Generated by Django 5.2.6 on 2025-09-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedownloadtask',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', '待处理'), ('processing', '处理中'), ('downloading', '下载中'), ('completed', '已完成'), ('partial_completed', '部分完成'), ('failed', '失败')], default='pending', help_text='任务状态', max_length=20, null=True),
        ),
    ]
