# Generated by Django 5.2.6 on 2025-09-24 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_imagedownloadtask_status'),
        ('polygons', '0002_alter_polygon_wgs84_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satelliteimage',
            name='task',
        ),
        migrations.AddField(
            model_name='satelliteimage',
            name='polygon',
            field=models.ForeignKey(default=1, help_text='关联多边形区域', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='polygons.polygon'),
            preserve_default=False,
        ),
    ]
