# Generated by Django 5.2.6 on 2025-09-26 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_satelliteimage_task_satelliteimage_polygon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedownloadtask',
            name='satellite',
        ),
    ]
