# Generated by Django 5.2.6 on 2025-09-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_imagedownloadtask_satellite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedownloadtask',
            name='end_time',
            field=models.DateField(help_text='时间范围结束'),
        ),
        migrations.AlterField(
            model_name='imagedownloadtask',
            name='start_time',
            field=models.DateField(help_text='时间范围开始'),
        ),
    ]
