# Generated by Django 5.2.6 on 2025-09-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_imagedownloadtask_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satelliteimage',
            name='shoot_time',
            field=models.DateField(help_text='拍摄时间'),
        ),
    ]
