# Generated by Django 5.2.6 on 2025-09-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_satelliteimage_shoot_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedownloadtask',
            name='downloaded_images_count',
            field=models.IntegerField(blank=True, default=0, help_text='下载的影像数量', null=True),
        ),
    ]
