# Generated by Django 5.2.6 on 2025-09-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_alter_imagedownloadtask_downloaded_images_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagedownloadtask',
            old_name='end_time',
            new_name='end_day',
        ),
        migrations.RenameField(
            model_name='imagedownloadtask',
            old_name='start_time',
            new_name='start_day',
        ),
        migrations.AlterField(
            model_name='imagedownloadtask',
            name='name',
            field=models.CharField(default='未命名任务', help_text='任务名称', max_length=200),
        ),
    ]
