# Generated by Django 5.2.6 on 2025-10-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_rename_end_time_imagedownloadtask_end_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satelliteimage',
            name='cloud_coverage',
        ),
    ]
