# Generated by Django 5.2.6 on 2026-08-25 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0009_remove_satelliteimage_cloud_coverage"),
        ("polygons", "0003_polygon_wgs84_shp_dir"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagedownloadtask",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Image download task",
                "verbose_name_plural": "Image download tasks",
            },
        ),
        migrations.AlterModelOptions(
            name="satelliteimage",
            options={
                "ordering": ["-shoot_time"],
                "verbose_name": "Satellite image",
                "verbose_name_plural": "Satellite images",
            },
        ),
        migrations.AlterField(
            model_name="imagedownloadtask",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, help_text="Completion time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="imagedownloadtask",
            name="downloaded_images_count",
            field=models.IntegerField(
                blank=True, default=0, help_text="Downloaded image count", null=True
            ),
        ),
        migrations.AlterField(
            model_name="imagedownloadtask",
            name="end_day",
            field=models.DateField(help_text="End of date range"),
        ),
        migrations.AlterField(
            model_name="imagedownloadtask",
            name="error_message",
            field=models.TextField(blank=True, help_text="Error message", null=True),
        ),
        migrations.AlterField(
            model_name="imagedownloadtask",
            name="name",
            field=models.CharField(
                default="Untitled task", help_text="Task name", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="imagedownloadtask",
            name="polygon",
            field=models.ForeignKey(
                help_text="Target polygon area",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="download_tasks",
                to="polygons.polygon",
            ),
        ),
        migrations.AlterField(
            model_name="imagedownloadtask",
            name="progress",
            field=models.IntegerField(
                default=0, help_text="Download progress (percent)"
            ),
        ),
        migrations.AlterField(
            model_name="imagedownloadtask",
            name="start_day",
            field=models.DateField(help_text="Start of date range"),
        ),
        migrations.AlterField(
            model_name="imagedownloadtask",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("downloading", "Downloading"),
                    ("completed", "Completed"),
                    ("partial_completed", "Partially completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Task status",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="satelliteimage",
            name="download_url",
            field=models.URLField(
                blank=True, help_text="Source download URL", null=True
            ),
        ),
        migrations.AlterField(
            model_name="satelliteimage",
            name="file_size",
            field=models.BigIntegerField(
                blank=True, help_text="File size (bytes)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="satelliteimage",
            name="image",
            field=models.ImageField(
                blank=True, help_text="Image file", null=True, upload_to="images/"
            ),
        ),
        migrations.AlterField(
            model_name="satelliteimage",
            name="image_identifier",
            field=models.CharField(
                blank=True,
                help_text="Satellite image identifier",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="satelliteimage",
            name="name",
            field=models.CharField(help_text="Image name", max_length=100),
        ),
        migrations.AlterField(
            model_name="satelliteimage",
            name="polygon",
            field=models.ForeignKey(
                help_text="Associated polygon area",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="polygons.polygon",
            ),
        ),
        migrations.AlterField(
            model_name="satelliteimage",
            name="satellite",
            field=models.CharField(
                choices=[
                    ("sentinel-1", "sentinel-1"),
                    ("sentinel-2", "sentinel-2"),
                    ("smap", "smap"),
                ],
                help_text="Satellite type",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="satelliteimage",
            name="shoot_time",
            field=models.DateField(help_text="Acquisition date"),
        ),
    ]
